### ISSUE TITLE
libpng error: PNG file corrupted by ASCII conversion

### ISSUE THREAD

**Issue by dbitouze** [cereda/sillypage#1]
Many thanks for this silly (and hilarious) package! :smile: 

# Context

- Linux Mageia 8.
- TeX Live 2021 (vanilla install).

# Issue

With:
```latex
\documentclass{article}
\usepackage{sillypage}
\begin{document}
\pagenumbering{silly}
Foo.
\end{document}
```
the compilation fails with the following error:
```
$ pdflatex test
[...]
(/usr/local/texlive/2021/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
libpng error: PNG file corrupted by ASCII conversion

!pdfTeX error: pdflatex (file /usr/local/texlive/2021/texmf-dist/tex/latex/sill
ypage/sillywalk-map.png): libpng: internal error
 ==> Fatal error occurred, no output PDF file produced!
```

**Comment by cereda** [comment]
Thank you so much for the report, Denis! I found out that issue as well, much to my dismay. :rofl: 

The culprit is a corrupted `sillywalk-map.png`. I don't know where exactly it failed (with `l3build` or during the upload), but I just sent an updated version to CTAN. So very sorry!

Of course, there had to be a silly error. :rofl: 

I will keep this issue open until CTAN's deployment, if it's okay. Thanks! :wink:

**Comment by cereda** [comment]
It was a blip with CTAN, already fixed. I am very surprised it wasn't my fault at all! :wink:

Hopefully, TL will be updated soon. Thanks again!
